[android] Fix `UnsupportedOperationException` and `NoSuchMethodError` on Android 7.x (#48577)
## Why

Apps with observe crashed on Android 7 (SDK 24 and 25). The main cause
is using the unsupported functions:
- `CopyOnWriteArrayList.removeIf` 
- `ThreadLocal.withInitial`

## How

Replace these functions with code fully supported on SDK 24 

## Test

Run the app with and without these changes on Android 7 emulator
(requires x86 architecture)

---------

Co-authored-by: Expo Bot <34669131+expo-bot@users.noreply.github.com>